### ISSUE TITLE
TypeAhead: typing in filter name and hitting enter gives a grayed out filter with no name

### ISSUE THREAD

**Issue by bsbeeks** [mxenabled/mx-react-components#23]
Steps to duplicate:

1. Type in a letter and then hit the enter key.
2. A tag will be added to the UI with nothing in it

<img width="387" alt="screenshot 2015-10-02 15 26 32" src="https://cloud.githubusercontent.com/assets/714084/10258224/fd5c64e6-6919-11e5-9c5f-9cbde6b080fb.png">

Implementation:

- [ ] Fork the repo
- [ ] run `npm install`
- [ ] run `npm run demo`. This will open up a new browser window with demos of each component. It will refresh whenever you save changes to the files in the `src` directory.
- [ ] open up `src/components/TypeAhead.js`
- [ ] On line 23, add another condition that will check if `highlightedValue` (the input value) is in `filteredItems` (the remaining available options). Hint: you'll want to use `.indexOf()`.
- [ ] Open the demo and make sure you can no longer replicate the bug.
- [ ] Do a quick run through of the TypeAhead functionality and make sure your changes didn't effect anything else.
- [ ] run `eslint src` to check for syntax and style errors. Fix the errors as needed.
- [ ] Commit your changes to the `src/` directory
- [ ] Push your changes to your fork
- [ ] Create a PR and include `Fixes #23` in the message
- [ ] Get merged and celebrate :tada:

**Comment by kentcdodds** [comment]
Super pleased to see that you're using the `first-timers-only` label. Something that's a big part of the `first-timers-only` label is that you give much more than a normal issue. You need to not only give step-by-step bug reproduction instructions, but also step-by-step implementation instructions.

This is about getting people to learn about contributing, not getting people to figure out the implementation. You don't want the implementation to get in the way of first time contributors. That's why in [my post](https://medium.com/@kentcdodds/first-timers-only-78281ea47455) I explain that it takes **more** work to get first timer contributions, not less.

I hope you and I can work to get more people involved in open source by making our open source projects an open and friendly place to new contributors! :+1:

**Comment by bsbeeks** [comment]
@kentcdodds awesome feedback. I'll have to review your article again and make sure we include more implementation information with each feature.

**Comment by kentcdodds** [comment]
:+1: I've seen a lot of people simply slap on a `first-timers-only` label and expect to get the results I've gotten. I hope that by making it even easier you can bring more people into the world of OSS :-)
