### ISSUE TITLE
Address Accessibility

### ISSUE THREAD

**Issue by bsbeeks** [mxenabled/mx-react-components#30]

**Comment by psigns** [comment]
Hi Brandon,

I see that this issue already has an assignee, but I'm really interested in learning more about accessibility.  Do you mind if I work on some of the components and make some pull requests?

**Comment by bsbeeks** [comment]
@psigns we'd love some help! Feel free to put up as many PR's as you'd like :+1:

**Comment by psigns** [comment]
Just checking in on this.  I've made the Range Selector, Icon, Toggle Switch, and DonutChart more accessible.  I'm going to work on the modals next, then I'll spend tomorrow working on the pull request.  I'll get to the TypeAhead component after the first pull request, because I can tell that its going to take some time.

**Comment by bsbeeks** [comment]
@psigns nice! Could you put up some PRs with the changes so we can start reviewing them? If possible, separate each component into it's own PR.

**Comment by cerinman** [comment]
This issue is very old and very broad.  Closing for now.  We can open individual issues for components as needed.
